name: Base wf1

on:
  workflow_dispatch:

jobs:
  tagme_head1:
    runs-on: ubuntu:latest
    name: DL the repo
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name:
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -s v1.2.3 -m "Stable promotion for v1.2.3"
          git push origin master
