name: Base wf

on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu:latest
    name: DL the repo
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
  second_job:
    needs: [first_job]
    runs-on: ubuntu:latest
    strategy:
      matrix:
        some: |
          a
          b
          c
          d
    steps:
      - name: echo the matrix value
        run: echo ${{ matrix.some }}
